import "../styles/globals.css";
import { League_Spartan } from "next/font/google";

const font = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "SaveUNight",
  description: "Generated by Breno Leite",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${font.className} containerBackground`}>
        {children}
      </body>
    </html>
  );
}
